# -*- coding: utf-8 -*-
"""type_speed.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sen6P0IeLD9Z_7eNxwFY06aBuLEAzz0x
"""

!pip install pyinstaller

from time import *
import random as r

print(time())


def mistake(par, usr):
  error=0
  for i in range(len(par)):
    try:
      if par[i]!=usr[i]:
        error=error+1
    except:
      error=error+1
  return error

def speed_time(t_s, t_e, user):
  time_delay=t_e-t_s
  t_r=round(time_delay,2)
  speed=len(user)/t_r
  return round(speed)


if __name__=='__main__':

  while True:
    ck=input("Ready for test : Yes / No\n")
    if ck=="Yes":
      test=["The tiger is a wild animal. It lives in forests. It belongs to the family of mammals. The tiger is also referred to as a big cat. The tiger is marked by stripes on its coat. Each tiger has a unique pattern of stripes, and one tiger can be distinguished from another by its stripe pattern. The tiger is a carnivorous animal. It preys on animals like the different species of deer, wild buffaloes, goats and boar that also inhabit the forest. There are different sub-species of the tiger such as the royal Bengal tiger, Sumatran tiger and Siberian tiger.",
            "The cow is a domestic animal one sees every day. Cows are found worldwide in various shapes, colours, and sizes. There are more than 1000 cow breeds in the world. Cows are the female mammal, and the male cow is called the Ox or Bull. A male cow’s child is known as a ‘Calf,’ while a female cow’s child is known as a ‘Heifer.’ Like most animals, cows have two eyes and ears, a nose, a long tail, four limbs, and two sharp horns. People keep cows at home for various reasons, including the provision of milk and making other dairy products from that milk. Cows are also bred for ploughing the fields or pulling the carts. They are peaceful animals, and are gentle and caring in nature.",
            "The Ganga is India's most important and iconic river. It flows down from its glacial source in the high Himalayas to course through five states in the northern plains before draining into the swirling waters of the Bay of Bengal through the Sunderbans delta, the largest mangrove system in the world. Along its 2,500 km journey, the river enriches huge swathes of agricultural land and sustains a long procession of towns and cities."]
      test1=r.choice(test)
      print("*****Typing speed calculator*****")
      print(f"{test1}\n\n")

      time1=time()
      testinput=input("Enter your text:\n")
      time2=time()

      print(f'speed : {speed_time(time1, time2, testinput)} word / second')
      print(f'Error : {mistake(test1, testinput)}')

    elif ck=="No":
      print("Thank You")
      break

    else:
      print("Invalid INput")